# PYNQ-Z2 (XC7Z020-1CLG400C) PL pins from the TUL reference manual v1.0.

# 125 MHz reference clock from the Ethernet-PHY oscillator.
set_property PACKAGE_PIN H16 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 8.000 -name sys_clk [get_ports sys_clk]

# Push buttons are active-high when pressed; BTN0 is the Nano reset input.
set_property PACKAGE_PIN D19 [get_ports {btn[0]}]
set_property PACKAGE_PIN D20 [get_ports {btn[1]}]
set_property PACKAGE_PIN L20 [get_ports {btn[2]}]
set_property PACKAGE_PIN L19 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[*]}]

# Four anode-connected user LEDs are active-high.
set_property PACKAGE_PIN R14 [get_ports {led[0]}]
set_property PACKAGE_PIN P14 [get_ports {led[1]}]
set_property PACKAGE_PIN N16 [get_ports {led[2]}]
set_property PACKAGE_PIN M14 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

# PL UART TX on Raspberry-Pi header pin 37 (Zynq PL pin W9).  This is an
# external 3.3 V TTL signal; the on-board FT2232 bridge is connected to PS MIO.
set_property PACKAGE_PIN W9 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property DRIVE 8 [get_ports uart_tx]
set_property SLEW SLOW [get_ports uart_tx]

# reset_request is generated by sys_clk and sampled by the first register of
# the CPU-domain reset synchronizer.  Only that CDC data path is intentionally
# unconstrained; the second synchronizer stage and CPU logic remain timed.
set_false_path -to [get_pins -hierarchical -regexp {.*reset_cpu_sync_reg\[0\]/D}]
