`timescale 1ns / 1ps

// PL-only platform shell intended for an RT-Thread Nano image.
//
// Address map:
//   0x8000_0000 .. RESET_PC + IMEM_WORDS*4 : instruction ROM
//   0x8010_0000 .. DATA_BASE + DMEM_BYTES  : byte-write data RAM
//   0x0200_0000 / +0x4000                  : machine timer (CLINT subset)
//   0x1000_0000 .. +0x000c                 : polling UART
//   0x8020_0040                             : LED write register
//
// The shell intentionally has no PS7, AXI, cache, or DMA dependency.  The
// same top can therefore be simulated with XSim today and connected to the
// PYNQ-Z2 PL clock/UART pins later.  A future PS adapter can use the exposed
// request/response and debug signals without changing the Core contract.
module rv32_nano_soc #(
    parameter integer IMEM_WORDS = 16384,
    parameter integer DMEM_BYTES = 32768,
    parameter logic [31:0] RESET_PC = 32'h8000_0000,
    parameter logic [31:0] DATA_BASE = 32'h8010_0000,
    parameter logic [31:0] LED_ADDR = 32'h8020_0040,
    parameter logic [31:0] TIMER_BASE = 32'h0200_0000,
    parameter logic [31:0] UART_BASE = 32'h1000_0000,
    parameter integer UART_CLK_HZ = 80_000_000,
    parameter integer UART_BAUD = 115_200,
    parameter string IMEM_INIT_FILE = "",
    parameter string DMEM_INIT_FILE = ""
) (
    input  logic        clk,
    input  logic        reset,
    output logic [3:0]  led,
    output logic        uart_tx,
    output logic        uart_tx_busy,
    output logic        uart_tx_valid,
    output logic [7:0]  uart_tx_data,
    output logic        status_running,
    output logic [31:0] cycle_count,
    output logic [31:0] retired_count,
    output logic        debug_wb_have_inst,
    output logic [31:0] debug_wb_pc
);
    localparam logic [31:0] DATA_END = DATA_BASE + DMEM_BYTES;

    logic        imem_req_valid;
    logic [31:0] imem_req_addr;
    logic        imem_rsp_valid;
    logic [31:0] imem_rsp_data;
    logic        rom_data_req_valid;
    logic [31:0] rom_data_req_addr;
    logic        rom_data_rsp_valid;
    logic [31:0] rom_data_rsp_data;

    logic        dmem_req_valid;
    logic        dmem_req_write;
    logic [31:0] dmem_req_addr;
    logic [3:0]  dmem_req_wstrb;
    logic [31:0] dmem_req_wdata;
    logic        dmem_rsp_valid;
    logic [31:0] dmem_rsp_rdata;

    logic        ram_req_valid;
    logic        ram_rsp_valid;
    logic [31:0] ram_rsp_rdata;
    logic        timer_rsp_valid;
    logic [31:0] timer_rsp_rdata;
    logic        timer_irq;
    logic        uart_rsp_valid;
    logic [31:0] uart_rsp_rdata;
    logic        uart_write_pulse;
    logic [7:0]  uart_write_data;
    logic        status_done;
    wire         cpu_clk = clk;

    assign status_running = !reset && !status_done;
    assign ram_req_valid  = dmem_req_valid &&
                            (dmem_req_addr >= DATA_BASE) &&
                            (dmem_req_addr < DATA_END);

    // A response is generated by exactly one target for each read request.
    // The priority mux also makes the contract explicit if a future map is
    // extended with overlapping windows.
    always_comb begin
        dmem_rsp_valid = ram_rsp_valid | rom_data_rsp_valid |
                          timer_rsp_valid | uart_rsp_valid;
        if (timer_rsp_valid)
            dmem_rsp_rdata = timer_rsp_rdata;
        else if (uart_rsp_valid)
            dmem_rsp_rdata = uart_rsp_rdata;
        else if (rom_data_rsp_valid)
            dmem_rsp_rdata = rom_data_rsp_data;
        else
            dmem_rsp_rdata = ram_rsp_rdata;
    end

    // Permit ordinary loads from the executable image.  This is required for
    // C string literals, RT-Thread init tables, and the startup .data copy in
    // a Harvard PL shell where instruction ROM is otherwise not on dmem.
    assign rom_data_req_valid = dmem_req_valid && !dmem_req_write &&
                                (dmem_req_addr >= RESET_PC) &&
                                (dmem_req_addr < RESET_PC + IMEM_WORDS * 4);
    assign rom_data_req_addr = dmem_req_addr;

    myCPU_sync core (
        .cpu_clk(cpu_clk), .cpu_rst(reset), .timer_irq(timer_irq),
        .imem_req_valid(imem_req_valid), .imem_req_addr(imem_req_addr),
        .imem_rsp_valid(imem_rsp_valid), .imem_rsp_data(imem_rsp_data),
        .dmem_req_valid(dmem_req_valid), .dmem_req_write(dmem_req_write),
        .dmem_req_addr(dmem_req_addr), .dmem_req_wstrb(dmem_req_wstrb),
        .dmem_req_wdata(dmem_req_wdata), .dmem_rsp_valid(dmem_rsp_valid),
        .dmem_rsp_rdata(dmem_rsp_rdata),
        .debug_wb_have_inst(debug_wb_have_inst), .debug_wb_pc(debug_wb_pc),
        .debug_wb_ena(), .debug_wb_reg(), .debug_wb_value()
    );

    rv32_sync_rom #(
        .DEPTH_WORDS(IMEM_WORDS), .BASE_ADDR(RESET_PC),
        .INIT_FILE(IMEM_INIT_FILE)
    ) imem (
        .clk(clk), .req_valid(imem_req_valid), .req_addr(imem_req_addr),
        .rsp_valid(imem_rsp_valid), .rsp_data(imem_rsp_data),
        .data_req_valid(rom_data_req_valid), .data_req_addr(rom_data_req_addr),
        .data_rsp_valid(rom_data_rsp_valid), .data_rsp_data(rom_data_rsp_data)
    );

    rv32_sync_byte_ram #(
        .DEPTH_BYTES(DMEM_BYTES), .BASE_ADDR(DATA_BASE),
        .INIT_FILE(DMEM_INIT_FILE)
    ) dmem (
        .clk(clk), .req_valid(ram_req_valid), .req_write(dmem_req_write),
        .req_addr(dmem_req_addr), .req_wstrb(dmem_req_wstrb),
        .req_wdata(dmem_req_wdata), .rsp_valid(ram_rsp_valid),
        .rsp_rdata(ram_rsp_rdata)
    );

    rv32_machine_timer #(.BASE_ADDR(TIMER_BASE)) timer (
        .clk(clk), .reset(reset), .req_valid(dmem_req_valid),
        .req_write(dmem_req_write), .req_addr(dmem_req_addr),
        .req_wstrb(dmem_req_wstrb), .req_wdata(dmem_req_wdata),
        .rsp_valid(timer_rsp_valid), .rsp_rdata(timer_rsp_rdata),
        .timer_irq(timer_irq)
    );

    rv32_uart #(
        .BASE_ADDR(UART_BASE), .CLK_HZ(UART_CLK_HZ), .BAUD(UART_BAUD)
    ) uart (
        .clk(clk), .reset(reset), .req_valid(dmem_req_valid),
        .req_write(dmem_req_write), .req_addr(dmem_req_addr),
        .req_wstrb(dmem_req_wstrb), .req_wdata(dmem_req_wdata),
        .rsp_valid(uart_rsp_valid), .rsp_rdata(uart_rsp_rdata),
        .tx(uart_tx), .tx_busy(uart_tx_busy),
        .tx_write_pulse(uart_write_pulse), .tx_write_data(uart_write_data)
    );

    always_ff @(posedge clk) begin
        if (reset) begin
            led           <= 4'd0;
            cycle_count   <= 32'd0;
            retired_count <= 32'd0;
            status_done   <= 1'b0;
        end else begin
            cycle_count <= cycle_count + 32'd1;
            if (debug_wb_have_inst)
                retired_count <= retired_count + 32'd1;

            if (dmem_req_valid && dmem_req_write &&
                dmem_req_addr == LED_ADDR && |dmem_req_wstrb)
                led <= dmem_req_wdata[3:0];

            // A write to LED_ADDR is the visible application result.  Keep a
            // separate done bit optional and non-invasive: Nano tasks are
            // normally long-running, so only an explicit all-ones write to
            // LED_ADDR+4 is treated as a simulation completion marker.
            if (dmem_req_valid && dmem_req_write &&
                dmem_req_addr == (LED_ADDR + 32'd4) &&
                dmem_req_wstrb == 4'b1111 && dmem_req_wdata == 32'h1)
                status_done <= 1'b1;
        end
    end

    assign uart_tx_valid = uart_write_pulse;
    assign uart_tx_data  = uart_write_data;
endmodule
